### ISSUE TITLE
routing test

### ISSUE THREAD

**Issue by y-akamatsu** [y-akamatsu/AkamatsuTrivialQuiz-API#20]
やりたいこと
ルーティングのテストコードの実装
renderファイルとapiファイルのrouteファイルの2種類のテストファイルを用意

superTestというモジュールを使用する
https://github.com/visionmedia/supertest

参考記事
https://qiita.com/mikakane/items/312f901850cc33b3b07b

重要箇所
テストしたいことの内容と実装内容
requireで読み込むファイル
各プロパティの理解
(text,stauts,body)
https://github.com/visionmedia/supertest#api

**Comment by y-akamatsu** [comment]
今回出たエラー
エラー1
```
Cannot read property 'apply' of undefined
at /Users/Tsuyoshi/Desktop/menta/akamatsu/AkamatsuTrivialQuiz-API/node_modules/express/lib/router/index.js:635:15
      at next (node_modules/express/lib/router/index.js:260:14)
      at Function.handle (node_modules/express/lib/router/index.js:174:3)
      at Server.router (node_modules/express/lib/router/index.js:47:12)
      at parserOnIncoming (_http_server.js:672:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
```

解決方法
エラー内容に自分の記述したファイルが表示されていないかつモジュール内のエラーだというのが分かるので
そもそもライブラリの使い方が違うのでドキュメントを再度確認する
またconosole.logを埋め込み思うよなデータが入っているのかも都度確認する。
https://github.com/visionmedia/supertest
